language: node_js

node_js:
  - 0.10
    
before_script:
  - npm link
  - mkdir -p shippable/codecoverage

after_success:
#  - npm run coverage
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - mocha test -R mocha-lcov-reporter  && 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
  - cat ./coverage/lcov.info | codeclimate

addons:
  code_climate:
    repo_token:
	  secure: "<ADD YOUR REPO TOKEN FOR CODECLIMATE>"



deploy:
  provider: npm
  email: guri1234@netvision.net.il

  api_key:
    secure: 
  on:
    tags: true
    all_branches: true
    repo: guri/try-yo-ionic-famous
